spring:
  application:
    name: "spring-kotlin-app"
server:
  servlet:
    context-path: /

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    metrics:
      enabled: true
      health:
        enabled: true
        show-components: "always"
        show-details: "always"
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
      environment: ${application.environment}
    distribution:
      slo:
        http.server.requests: 50ms
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.99
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
